remote_theme: marella/jekyll-theme-documentation
plugins_dir:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
title: Tapis Tutorials
description: NSF-funded API platform for computational research tutorials
baseurl: "/tutorials"
url: "http://localhost:4000"

# Build settings
markdown: kramdown
permalink: pretty

nav:
  - Home:
      - Home: ''
  - Introduction and Prerequisites:
      - Introduction: intro/intro
  - Registering Systems and Managing Data:
      - Hello, Tapis: hello/hello
      - Intro to Systems: systems/intro
      - Creating an HPC System: systems/hpc
      - Registering System Credentials: systems/credentials
      - Managing Data on a System: files/data
  - Creating Applications and Running Jobs:
      - Intro to Apps: apps/intro
      - Creating and Registering a Classifier app: apps/hello
      - Executing the Classifier app: jobs/hello
  - All Tapis Systems Tutorials:
      - Intro to Systems: systems/intro
      - Registering a Server: systems/vm
      - Registering an HPC System: systems/hpc
      - Registering an S3 Bucket System: systems/s3
      - Registering System Credentials: systems/credentials
  - All Tapis Apps Tutorials:
      - Intro to Apps: apps/intro
      - Creating and Registering a Classifier app: apps/hello
  - All Tapis Jobs Tutorials:
      - Intro to Jobs: jobs/intro
  - All Tapis Pods Tutorials:
      - Intro to Pods: pods/intro