# theme: jekyll-theme-minimal
remote_theme: marella/jekyll-theme-documentation

permalink: pretty
baseurl: "/tutorials"
nav:
- AI/ML, The National CI Ecosysystem, and Tapis:
  - (Lecture) AI, CI and Tapis: ./Intro_Tapis/01-intro-to-tapis
  - (Hands-on) Initial Steps with TapisUI: ./Intro_Tapis/02-initial-tapis-ui
- AI Models and Fleserv:
  - (Lecture) Classes of AI Models, 3rd Party Model Registries, Flexserv: ./Tapis_FlexServ/01-lecture
  - (Hands-on) Executing Large Models on Vista Via Tapis and Flexserv: ./Tapis_FlexServ/01b-running-flexserv
- Vision Models, Fine-tuning and Jupyter Notebooks:
  - Vision Models in Science: ./Vision_Models/01-intro-vision-models
  - (Hands-on) Launching Juptyer Notebook: ./Jupyter-Notebook/intro-to-jupyter 
  - Prompt Engineering and Detection Code: ./Tapis_FlexServ/01c-code-gen-flexserv
  - Fine-tuning with Ultralytics: ./Fine_Tuning_Vision/01-intro-fine-tuning
- Evaluating Fine-tuned Models:
  - Evaluating our New Model: ./Fine_Tuning_Vision/02-evaluation 
  #- Prompt Engineering: ./Vision_Models/02-prompt-engineering 
theme: jekyll-theme-minimal
