# theme: jekyll-theme-minimal
remote_theme: marella/jekyll-theme-documentation

permalink: pretty
baseurl: "/tutorials"
nav:
- AI/ML, The National CI Ecosysystem, and Tapis:
  - AI, CI and Tapis: ./Intro_Tapis/01-intro-to-tapis
  - Initial Steps with TapisUI: ./Intro_Tapis/02-initial-tapis-ui
- AI Models and Fleserv:
  - Classes of AI Models and the AI Ecosysystem: ./Tapis_FlexServ/01-lecture
  - Hands-on Flexserv TapisUI Tutorial: ./Tapis_FlexServ/01b-running-flexserv
- Vision Models and Jupyter Notebooks:
  - Vision Models in Science: ./Vision_Models/01-intro-vision-models
  - Intro to Jupyter: ./Jupyter-Notebook/intro-to-jupyter 
  - Prompt Engineering: ./Vision_Models/02-prompt-engineering 
- Fine-tuning Vision Models:
  - Fine-tuning with Ultralytics: ./Fine_Tuning_Vision/01-intro-fine-tuning
  - Evaluating our New Model: ./Fine_Tuning_Vision/02-evaluation 
theme: jekyll-theme-minimal
